version: "3"

services:
  development-digitaltwin:
    container_name: development-chat
    build:
      context: ../
      dockerfile: ./dev/Dockerfile
    restart: always
    volumes:
      - ../frontend:/frontend
      - ../backend:/backend
      - ./appdata:/appdata
      # - ./dev/logs:/var/log/
      # - ./dev/logs:/var/log

    networks:
      - chatnet
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun

networks:
  chatnet:
    external: true