version: "3"

services:
  jensmeire-digitaltwin:
    container_name: jensmeire-chat
    build:
      context: ../
      dockerfile: ./dev/Dockerfile
    restart: always
    environment:
      - USER_ID=jensmeire
      - ENVIRONMENT=development
    volumes:
      - ../frontend:/frontend
      - ../backend:/backend
      - /appdata:/appdata
      # - ./dev/logs:/var/log/
      # - ./dev/logs:/var/log

    networks:
      - chatnet
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun

#  testuser-digitaltwin:
#    container_name: testuser-chat
#    build:
#      context: ../
#      dockerfile: ./dev/Dockerfile
#    restart: always
#    environment:
#      - USER_ID=testuser
#      - ENVIRONMENT=development
#    volumes:
#      - ../frontend:/frontend
#      - ../backend:/backend
#      - /appdata2:/appdata
#     # - ./dev/logs:/var/log/
#     # - ./dev/logs:/var/log
#
#    networks:
#      - chatnet
#    sysctls:
#      - net.ipv6.conf.all.disable_ipv6=0
#    cap_add:
#      - NET_ADMIN
#    devices:
#      - /dev/net/tun

networks:
  chatnet:
    external: true
