version: "3"

services:
  jensmeire-digitaltwin:
    container_name: jensmeire-chat
    build:
      context: ../
      dockerfile: ./dev/Dockerfile
    restart: always
    environment:
      - USER_ID=jensmeire
      - ENVIRONMENT=development
    volumes:
      - ../frontend:/frontend
      - ../backend:/backend
      - ../publisher:/publisher
      - ~/.publisher:/root/.publisher
      - /appdata:/appdata
      # - ./dev/logs:/var/log/
      # - ./dev/logs:/var/log
    ports:
      - "443:443"
      - "80:3000"
    networks:
      - chatnet
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun

networks:
  chatnet:
    external: true
