name: staging

on:
  push:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get key
        run: ${{ secrets.SSH_KEY }}
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag threefoldjimber/digitaltwin:${{ github.sha }}
      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Push to dockerhub
        run: docker push threefoldjimber/digitaltwin:${{ github.sha }}
      - name: Push latest to dockerhub
        run: |
          docker tag threefoldjimber/digitaltwin:${{ github.sha }} threefoldjimber/digitaltwin:latest
          docker push threefoldjimber/digitaltwin:latest
          docker push threefoldjimber/digitaltwin:${{ github.sha }}
  deploy_staging:
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: digitaltwin.staging
      url: https://digitaltwin-test.jimbertesting.be/
    steps:
      - name: deploy on ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: docker pull threefoldjimber/digitaltwin:${{ github.sha }}
      - name: set new version in config
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: echo "threefoldjimber/digitaltwin:${{ github.sha }}" > '/etc/digitaltwin/version.txt'
